♻️ Tiny Improvements
HrikB/createXcrunch pull request #2
Opened 2024-02-03 16:18 UTC by pcaversaccio

This PR adds the following (mostly chore-related) changes:
- Adds a CI pipeline that checks the format for `md`, `yml`, `yaml`, and `rs` files, ensures no typos, and validates all links;
- Adds the ~~AGPL~~ MIT License if you're fine with it;
- Improves the docs;

2024-02-03 21:41 UTC, HrikB requested changes
This is sweet! For the license, let's do an MIT license instead?

2024-02-03 21:43 UTC, pcaversaccio commented
> This is sweet! For the license, let's do an MIT license instead?

Sure, will push tomorrow!

2024-02-04 11:26 UTC, pcaversaccio commented
> This is sweet! For the license, let's do an MIT license instead?

Fixed via f74e4cfeadce5e9257b61c3b6d507aad00aa23ff and 18b01c64c4d6ed6127644312fc9a36bc21835738.

2024-02-04 11:49 UTC, HrikB approved these changes

2024-02-04 11:50 UTC, merged